language: cpp
dist: trusty

before_install:
    # g++6
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  
    # Qt5
    - sudo apt-add-repository --yes ppa:canonical-qt5-edgers/ubuntu1204-qt5
    - sudo apt-get update -qq

install:
    # g++6
    - sudo apt-get remove g++
    - sudo apt-get install -qq g++-6
    
    # Qt5
    - yes | sudo apt-get install -qq --force-yes qtdeclarative5-dev

script:
    - qmake -project
    - qmake ./src/ChatBot.pro
    - make
