language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59[QTPACKAGE]

script:
  - source /opt/qt59/bin/qt59-env.sh
  - /opt/qt59/bin/qmake -project
  - /opt/qt59/bin/qmake ./src/ChatBot.pro
  - make