language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-6 qt57-meta-full

script:
    - qmake -project
    - qmake ./src/ChatBot.pro
    - make
